# Generated by Django 3.1.4 on 2020-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20201221_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='author_id',
            new_name='author',
        ),
    ]
