# Generated by Django 3.1.4 on 2020-12-21 19:27

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0006_auto_20201221_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='author',
        ),
        migrations.AddField(
            model_name='listing',
            name='author_id',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
