# Generated by Django 3.1.4 on 2020-12-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='post',
            new_name='Listing',
        ),
    ]
