# Generated by Django 3.1.4 on 2020-12-22 17:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20201222_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='Listing',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='listing', unique=True),
            preserve_default=False,
        ),
    ]
