# Generated by Django 3.1.4 on 2020-12-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20201222_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='listing',
            new_name='Listing',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='slug',
        ),
    ]
