# Generated by Django 3.1.4 on 2020-12-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20201222_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='Listing',
            new_name='listing',
        ),
    ]
